Repository InventorsDev/sdg-004, pull requests merged in 2021-04, with the labels that each got.

#11 Created dashboard for the reporter
  app/reporter.html
  css/app.css
  css/bootstrap-sidebar.min.css
  images/avatar.jpg
  images/female-avatar.png
  images/speakup1.png
  js/bootstrap.bundle.min.js
  js/jquery-sidebar.min.js
  js/sidebar-bootstrap.min.js
Labels: Code

#17 Implemented the chatbot feature and also updated the js and css files
  css/style.css
  index.html
  js/custom.js
Labels: Code, enhancement

#18 Merge to development branch
  css/style.css
  index.html
Labels: Code, enhancement

#20 Perfected the achievement section
  css/style.css
  index.html
Labels: bug

#21 Created and implemented responder.html file in app folder
  app/responder.html
Labels: Code, enhancement

#23 Implemented the How it Works section of the index page
  css/style.css
  images/howit-bg.png
  index.html
Labels: Code, enhancement

#26 Implemented the login interface
  css/style.css
  index.html
  login.html
Labels: Code, enhancement

#27 Updated custom.js for user login validation
  js/custom.js
Labels: Code, enhancement

#30 Implemented the signup section and updated the login page
  css/style.css
  images/loading.gif
  js/custom.js
  login.html
  signup.html
Labels: Code, enhancement

#35 Modified project for backend
  .htaccess
  ajaxfile.php
  app/reporter.php
  app/responder.php
  config.php
  css/style.css
  index.php
  js/custom.js
  login.php
  signup.php
  speakup.sql
Labels: Code

#36 Completed signup and login backend
  ajaxfile.php
  css/style.css
  cv/EGIFFORD@MVCC.EDUw_cv.docx
  js/custom.js
  login.php
  signup.php
Labels: Code, enhancement

#38 Development
  ajaxfile.php
  css/style.css
  images/tips/tips-image1.jpg
  images/tips/tips-image2.jpg
  images/tips/tips-image3.jpg
  images/tips/tips-image4.jpg
  index.php
  js/custom.js
  signup.php
  speakup.sql
  tips.php
Labels: Code

#45 Development: help module of the reporter and started the report tracking feature
  ajaxfile.php
  app/ajaxfile.php
  app/includes/navbar.php
  app/logout.php
  app/reporter.php
  app/reports.php
  app/responder.php
  css/app.css
  css/style.css
  functions.php
  images/female-avatar.png
  images/profile-image.jpg
  images/working-girl.png
  index.php
  js/app.js
  js/custom.js
  login.php
Labels: Code
