Repository InventorsDev/sdg-004, pull requests merged in 2021-05, with the labels that each got.

#50 Create composer.json
  composer.json
Labels: enhancement

#49 Completed user interfce
  .htaccess
  ajaxfile.php
  app/404.php
  app/ajaxfile.php
  app/data.php
  app/help.php
  app/includes/navbar.php
  app/index.php
  app/messages.php
  app/notifications.php
  app/profile.php
  app/reporter.php
  app/reports.php
  app/responder.php
  app/uploads/report_2_file_0.jpg
  app/uploads/report_2_file_1.pdf
  app/uploads/report_3_file_0.jpg
  app/uploads/report_3_file_1.jpg
  app/view-reports.php
  config.php
  css/app.css
  css/style.css
  cv/EGIFFORD@MVCC.EDUd3k_cv.pdf
  cv/EGIFFORD@MVCC.EDUw_cv.docx
  functions.php
  index.php
  js/Chart.min.js
  js/app.js
  js/custom.js
  login.php
  signup.php
  speakup.sql
  tips.php
Labels: Code, enhancement

#57 Update README.md
  README.md
Labels: enhancement

#58 Added screenshot image
  images/screenshot.png
Labels: enhancement

#59 Updated README.md file
  README.md
Labels: Code

#60 Merge to development branch
  README.md
  app/index.php
  app/reports.php
  config.php
  images/screenshot.png
  js/app.js
Labels: enhancement

#62 Updated custom.js
  js/custom.js
Labels: bug

#65 Updated config file for Heroku ClearDB connection information
  config.php
Labels: bug

#63 Development
  app/ajaxfile.php
  app/responder.php
  app/share-tips.php
  js/app.js
  tips.php
Labels: enhancement
